name: Backend CI
run-name: Running backend CI on commit ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      mode:
        default: 'test'
        required: true
        type: choice
        description: 'test or publish'
        options:
          - 'test'
          - 'publish'
  push:
    branches:
      - master
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'

env:
  ECR_REPOSITORY: '${{ vars.APP_NAME }}-${{ vars.ENVIRONMENT }}-backend-ecr'
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_IDS }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
  ECS_SERVICE:  '${{ vars.APP_NAME }}-${{ vars.ENVIRONMENT }}-backend-service'
  ECS_CLUSTER:  '${{ vars.APP_NAME }}-${{ vars.ENVIRONMENT }}-ecs-cluster'

jobs:
  test:
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.mode == 'test')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          docker build --target test -t flowershop-backend backend/

  publish:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.mode == 'publish')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses:  docker/login-action@v2
        with:
          registry: env.ECR_REGISTRY
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        id: run-tests
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --target test -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend/

      - name: Build, tag and push image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT