name: Backend CI/CD
run-name: Running backend CI/CD on commit ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      mode:
        default: 'test'
        required: true
        type: choice
        description: 'test or publish'
        options:
          - 'test'
          - 'publish'
          - 'publish-and-deploy'

  push:
    branches:
      - master
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  unit-tests:
    name: Running unit tests on image
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.mode == 'test')
    uses: ./.github/workflows/image-unit-test.yaml
    with:
      image-path: backend/

  push:
    name: Building, tagging and pushing image to ECR
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.mode == 'publish')
    uses: ./.github/workflows/image-push.yaml
    with:
      image-path: backend/
      image-tag: ${{ github.sha }}
      repository: ${{ vars.APP_NAME }}-${{ vars.ENVIRONMENT }}-backend-ecr
      registry: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
    secrets: inherit

  deploy:
    name: Deploying image to ECS
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.mode == 'publish-and-deploy')
    uses: ./.github/workflows/image-deploy-to-ecs.yaml
    with:
      app-name: ${{ vars.APP_NAME }}
      environment: ${{ vars.ENVIRONMENT }}
      aws-region: ${{ vars.AWS_REGION }}
      image: ${{ needs.push.outputs.image }}
      mode: backend
    secrets: inherit