name: Push image to ECR

on:
  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The tag of the image to push to ECR'
        required: true
      image-path:
        type: string
        description: 'The path to the Dockerfile'
        required: true
      repository:
        type: string
        description: 'The ECR repository'
        required: true
      registry:
        type: string
        description: 'The ECR registry'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ECR_REGISTRY: ${{ inputs.registry }}
      ECR_REPOSITORY: ${{ inputs.repository }}
      IMAGE_TAG: ${{ inputs.image-tag }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses:  docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run unit tests
        id: run-tests
        run: |
          docker build --target test -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend/
  
      - name: Build, tag and push image
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT